name: tambak_undang
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  fl_chart: ^0.63.0
  charts_flutter: ^0.12.0

  dio: ^5.3.1
  dartz: ^0.10.1
  shared_preferences: ^2.2.0
  calendar_date_picker2: ^0.5.2
  intl: ^0.17.0
  flutter_chart: ^0.1.6
  flutter_plot: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
